/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 basket_swing_chair.gltf --transform
Author: a.shevchuk (https://sketchfab.com/alex.shevchuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/basket-swing-chair-92463f2b44624180a4ed8488ce08eb83
Title: Basket Swing Chair
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/basket_swing_chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.part1_chair1_0.geometry} material={materials.PaletteMaterial001} />
    </group>
  )
}

useGLTF.preload('/basket_swing_chair-transformed.glb')
